<?php
$form = $this->form;
$form->prepare();
$hiddenInfoRegistro = '';
$action = $form->getAttribute('action');
if ($action == 'add') {
    $hiddenInfoRegistro = 'hidden';
}
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>Informacion del turno</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fk_usuario_id">Empleado <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fk_usuario_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechaInicio">fechaInicio <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechaInicio')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechaFinal">fechaFinal <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechaFinal')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="valorHora">valorHora <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('valorHora')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="horasTurno">minutosTurno <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('horasTurno')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pagoTotal">pagoTotal <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pagoTotal')); ?>
        </div>
    </div>


</fieldset>
<fieldset <?php echo $hiddenInfoRegistro; ?>>
    <legend>Informacion de Registro</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_turno_id">ID Turno</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pk_turno_id')); ?>
        </div>
    </div>
</fieldset>

<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <?php
        if ($action != 'buscar') {
            echo $this->formRow($form->get('btnCancelar'));
        }
        if ($action != 'detail' && $action != 'buscar') {
            echo $this->formSubmit($form->get('btnEnviar'));
        }
        ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
