<?php
$title = 'Reportes de turnos ';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'));

$this->headScript()->prependScript('$(document).ready(function() {'
                . '$("#tblTurnoes").DataTable({'
                . 'responsive: true,'
                . '"iDisplayLength": 25,
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                        "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                        "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        "sInfoEmpty": "Mostrando 0 A 0 registros",
                        "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                        "sLoadingRecords": "CARGANDO...",
                        "sProcessing": "EN PROCESO...",
                        "sSearch": "Buscar:",
                        "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        "oPaginate": {
                            "sFirst": "Inicio",
                            "sLast": "Fin",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        }
                    },
                    "aaSorting": [[0, "DESC"]]'
                . '});'
                . '});'
                , 'text/javascript'
                , array('noescape' => true))
        ->prependFile('/public/js/sistema/turno.js')
        ->prependFile('/public/vendors/iCheck/icheck.min.js')
        ->prependFile('/public/vendors/datatables.net-scroller/js/dataTables.scroller.min.js')
        ->prependFile('/public/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')
        ->prependFile('/public/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')
        ->prependFile('/public/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons/js/buttons.html5.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons/js/buttons.print.min.js')
        ->prependFile('/public/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')
        ->prependFile('/public/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')
        ->prependFile('/public/vendors/pdfmake/build/pdfmake.min.js')
        ->prependFile('/public/vendors/pdfmake/build/vfs_fonts.js')
        ->prependFile('/public/vendors/datatables.net/js/jquery.dataTables.min.js');

$form = $this->formTurno;
echo $this->form()->openTag($form);
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" style="color: #d98e3d; text-shadow: 1px 1px #efc614">REPORTES EN PDF <img src="/public/img/iconos/pdf.png"width="50" height="50"></h1>
    </div>
</div>
<fieldset>
    <p class="text-muted font-13 m-b-30">
        A continuacion se pueden descargar los reportes de los turnos de los empleados.
    </p>
</fieldset> 
<form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Empleado <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fk_usuario_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">F. Inicio <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechaReporteInicial')); ?>
        </div>
    </div>
    <div class="form-group">
        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">F. Final</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechaReporteFinal')); ?>
        </div>
    </div>
    <div class="ln_solid"></div>
    <div class="form-group">
        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button  type="button" class="btn btn-primary" name="botonFecha" id="botonFecha" onclick="downloadReporte()" value="Descargar" >Descargar &nbsp; <i class="fa fa-download" aria-hidden="true"></i> </button>
            <?php
            echo '<a href="' . $this->url('administracion/default', array('controller' => 'clienteempleado', 'action' => 'index')) . '"  class="btn btn-danger"> Cerrar</a>' . ' ';
            echo $this->form()->closeTag()
            ?>
        </div>
    </div>

</form>