<?php
$title = 'Personalizados';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'));

$this->headScript()->prependScript('$(document).ready(function() {'
                . '$("#tblPersonalizados").DataTable({'
                . 'responsive: true,'
                . '"iDisplayLength": 25,
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                        "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                        "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        "sInfoEmpty": "Mostrando 0 A 0 registros",
                        "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                        "sLoadingRecords": "CARGANDO...",
                        "sProcessing": "EN PROCESO...",
                        "sSearch": "Buscar:",
                        "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        "oPaginate": {
                            "sFirst": "Inicio",
                            "sLast": "Fin",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        }
                    },
                    "aaSorting": [[0, "des"]]'
                . '});'
                . '});'
                , 'text/javascript'
                , array('noescape' => true))
        ->prependFile($this->basePath('js/sistema/personalizado.js'))
        ->prependFile('http://maps.google.com/maps/api/js?language=es')
        ->prependFile($this->basePath('vendors/iCheck/icheck.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-scroller/js/dataTables.scroller.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/pdfmake.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/vfs_fonts.js'))
        ->prependFile($this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'));
?>
<div class="page-title">
    <div class="title_left">
        <h3><i class="fa fa-file-text"></i> Personalizado <small>PRINCIPAL</small></h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">IR!</button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Registros del Sistema <small>Personalizados</small></h2>
                <ul class="nav navbar-right panel_toolbox">                  
                    <!-- Split button -->
                    <div class="btn-group">
                        <button type="button" onclick="verAgregarPersonalizado()" class="btn btn-success"><i class="fa fa-plus"></i> Registrar Personalizados</button>
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="<?php echo $this->url('administracion/default', array('controller' => 'clienteempleado', 'action' => 'index')) ?>"><i class="fa fa-user"></i> Personal</a>
                            </li>
                            <li><a href="<?php echo $this->url('administracion/default', array('controller' => 'turno', 'action' => 'index')) ?>"><i class="fa fa-table"></i> Turnos</a>
                            </li>
                            <li><a href="<?php echo $this->url('administracion/default', array('controller' => 'personalizado', 'action' => 'index')) ?>"><i class="fa fa-cog fa-spin"></i> Personalizados</a>
                            </li>  
                            <li><a href="<?php echo $this->url('administracion/default', array('controller' => 'turno', 'action' => 'indexReporte')) ?>"><i class="fa fa-download"></i> Reportes</a>
                            </li>                  
                        </ul>
                    </div>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos los personalizados registrados en el sistema.
                </p>
                <table id="tblPersonalizados" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Usuario</th>                            
                            <th>Fecah Hora</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->personalizado as $personalizado) {//personalizado viene del metodo indexAction PersonalizadoController 
                            echo '<tr>';
                            echo '<td>' . $personalizado['personalizadoOBJ']->getpk_personalizado_id() . '</td>';
                            echo '<td>' . $personalizado['usuarioOBJ']->getNombreApellido() . '</td>';
                            echo '<td>' . $personalizado['personalizadoOBJ']->getFechaPersonalizado() . '</td>';
                            echo '<td>';
                            echo '<a href="" onclick="verEditar(' . $personalizado['personalizadoOBJ']->getpk_personalizado_id() . '); return false;" title="Editar este Personalizado"><i class="fa fa-edit"></i></a>';
                            echo '&nbsp;&nbsp;';
                            echo '<a href="" onclick="verDetalle(' . $personalizado['personalizadoOBJ']->getpk_personalizado_id() . '); return false;" title="Ver este Personalizado a Detalle"><i class="fa fa-eye"></i></a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Formulario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divContenido"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>POPGYM &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalAnexarUsuario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Seleccionar Usuario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divAnexarUsuario"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>PsicoTest &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>

