<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
//$formBusquedas = $this->formBusquedas;
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mensaje = 'VENTAS';
$tipo = 'info';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    foreach ($mensajes as $mensaje) {
        
    }
}
//------------------------------------------------------------------------------
$title = 'Ventas';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.buttons.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.nonblock.css'))
        ->prependStylesheet($this->basePath('/public/css/sweetalert2.min.css'));

$this->headScript()->prependScript('
                $(document).ajaxStop($.unblockUI); 
                $(document).ready(function() {
                     $("#tblVentas").DataTable({
                        "responsive": "true",
                        "iDisplayLength": 25,
                        "sPaginationType": "full_numbers",
                        "oLanguage": {
                            "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                            "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                            "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                            "sInfoEmpty": "Mostrando 0 A 0 registros",
                            "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                            "sLoadingRecords": "CARGANDO...",
                            "sProcessing": "EN PROCESO...",
                            "sSearch": "Buscar:",
                            "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                            "oPaginate": {
                                "sFirst": "Inicio",
                                "sLast": "Fin",
                                "sNext": "Siguiente",
                                "sPrevious": "Anterior"
                            }
                        },
                        "aaSorting": [[0, "asc"]]
                });
                    //------------------------------------------------------------------------------
                    // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                    //------------------------------------------------------------------------------
                    $("#modalFormulario").on("hide.bs.modal", function (e) {
                        return confirmarCerrar();
                    }); 
                    new PNotify({
                     title: "<br>SPARTANS<br>",
                     text: "' . $mensaje . '",
                     type: "' . $tipo . '",
                     styling: "bootstrap3"
                    });
                });', 'text/javascript', array('noescape' => true))
        ->prependFile($this->basePath('js/sistema/venta.js'))
        ->prependFile($this->basePath('js/jquery.blockUI.js'))
        ->prependFile($this->basePath('vendors/iCheck/icheck.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-scroller/js/dataTables.scroller.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/pdfmake.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/vfs_fonts.js'))
        ->prependFile($this->basePath('js/SwtSistema.js'))
        ->prependFile($this->basePath('js/sweetalert2.all.min2021.js'))
        ->prependFile($this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'))
        ->prependFile($this->basePath('vendors/pnotify/dist/pnotify.js'));
$formVenta = $this->form;
?>
<div class="clearfix"></div>
<div class="row">
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Registros del Sistema <small>Ventas</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>    
                        <div class="form-group">                      
                            <button type="button" onclick="seleccionarProducto(<?php echo $formVenta->get('pk_venta_id')->getValue(); ?>)" class="btn btn-info"><i class="fa fa-search"></i> Anexar Producto</button>
                        </div>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos los ventas registrados en el sistema.
                </p>
                <table id="tblVentas" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>Nombre</th>               
                            <th>Cantidad</th>
                            <th>Precio U.</th>
                            <th>Monto</th>                                    
                            <th></th>                                    
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->productos as $productos) {
                            echo '<tr>';
                            echo '<td>' . $productos['productoOBJ']->getNombreProducto() . " " . $productos['productoOBJ']->getDescripcion() . '</td>';
                            echo '<td>' . $productos['productoVentaOBJ']->getCantidadVenta() . '</td>';
                            echo '<td>$ ' . number_format($productos['productoOBJ']->getPrecioVenta()) . '</td>';
                            echo '<td>$ ' . number_format($productos['productoVentaOBJ']->getMonto()) . '</td>';
                            echo '<td>';
                            echo '<a href="javascript:eliminarArticulo(' . $productos['productoVentaOBJ']->getPk_venta_id() . ',' . $productos['productoVentaOBJ']->getPk_producto_id() . ')" title="ELIMINAR PRODUCTO"><i class="fa fa-close"></i></a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>

                    </tbody>
                    <tfoot><td></td><td></td><th style="background: #FFA">Total:</th>
                    <?php
                    $total = 0;
                    foreach ($this->productos as $suma) {
                        $total += $suma['productoVentaOBJ']->getMonto();
                    }
                    echo '<th style="background: #FFA">$ ' . number_format($total) . '</th>';
                    ?>
                    <td></td ></tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
    <?php
    echo '<a href="' . $this->url('administracion/default', array('controller' => 'venta', 'action' => 'index')) . '"  class="btn btn-danger"> Cerrar</a>' . ' ';
    echo $this->form()->closeTag()
    ?>

</div>
<div class="modal fade" id="modalAnexarProducto" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Seleccionar Producto</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divAnexarProducto"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>Jimmy90. &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalAddProducto" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Cantidad a comprar</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">  
                                <form class="form-horizontal form-label-left" action="<?php echo $this->url('administracion/default', array('controller' => 'venta', 'action' => 'setProductoVenta')) ?>" method="POST" onsubmit="return validarGuardar()">
                                    <div class="x_content" id="divAddProducto"></div>
                                    <div class="x_content" id="divContenido"></div>
                                    <input type="hidden" id="idVentaSelect" name="idVentaSelect">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>Jimmy90. &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div id="msgBloqueo" style="display: none;"> 
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE <i class="fa fa-spinner fa-spin fa-lg"></i>
</div>
<!-- PNotify -->
<script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.buttons.js'); ?>"></script>
<script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.nonblock.js'); ?>"></script>