<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
//$formBusquedas = $this->formBusquedas;
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mensaje = 'VENTAS';
$tipo = 'info';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    foreach ($mensajes as $mensaje) {
        
    }
}
//------------------------------------------------------------------------------
$title = 'Ventas';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.buttons.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.nonblock.css'))
        ->prependStylesheet($this->basePath('/public/css/sweetalert2.min.css'));


$this->headScript()->prependScript('
                $(document).ajaxStop($.unblockUI); 
                $(document).ready(function() {
                     $("#tblVentas").DataTable({
                        "responsive": "true",
                        "iDisplayLength": 25,
                        "sPaginationType": "full_numbers",
                        "oLanguage": {
                            "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                            "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                            "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                            "sInfoEmpty": "Mostrando 0 A 0 registros",
                            "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                            "sLoadingRecords": "CARGANDO...",
                            "sProcessing": "EN PROCESO...",
                            "sSearch": "Buscar:",
                            "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                            "oPaginate": {
                                "sFirst": "Inicio",
                                "sLast": "Fin",
                                "sNext": "Siguiente",
                                "sPrevious": "Anterior"
                            }
                        },
                        "aaSorting": [[0, "asc"]]
                });
                    //------------------------------------------------------------------------------
                    // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                    //------------------------------------------------------------------------------
                    $("#modalFormulario").on("hide.bs.modal", function (e) {
                        return confirmarCerrar();
                    }); 
                    new PNotify({
                     title: "<br>SPARTANS<br>",
                     text: "' . $mensaje . '",
                     type: "' . $tipo . '",
                     styling: "bootstrap3"
                    });
                });', 'text/javascript', array('noescape' => true))
        ->prependFile($this->basePath('js/sistema/venta.js'))
        ->prependFile($this->basePath('js/jquery.blockUI.js'))
        ->prependFile($this->basePath('vendors/iCheck/icheck.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-scroller/js/dataTables.scroller.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/pdfmake.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/vfs_fonts.js'))
        ->prependFile($this->basePath('js/SwtSistema.js'))
        ->prependFile($this->basePath('js/sweetalert2.all.min2021.js'))
        ->prependFile($this->basePath('vendors/pnotify/dist/pnotify.js'));
?>
<div class="page-title">
    <div class="title_left">
        <h3><i class="fa fa-file-text"></i> Venta <small>PRINCIPAL</small></h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">IR!</button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Registros del Sistema <small>Ventas</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>    
                        <button type="button" onclick="verAgregarVenta()" class="btn btn-success"><i class="fa fa-shopping-cart"></i> Registrar Ventas</button>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos los ventas registrados en el sistema.
                </p>
                <table id="tblVentas" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th><i class="fa fa-key"></i></th>                          
                            <th>Cantidad</th>
                            <th>Total</th>
                            <!--<th>Ganancia</th>-->
                            <th>Fecha</th>
                            <th title="OPCIONES"><i class="fa fa-cog fa-spin fa-lg"></i></th> 
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->venta as $venta) {//venta viene del metodo indexAction VentaController 
                            echo '<tr>';
                            echo '<td>' . $venta['ventaOBJ']->getPk_venta_id() . '</td>';
                            echo '<td>' . $venta['ventaOBJ']->getCantidadVenta() . '</td>';
                            echo '<td>' . number_format($venta['ventaOBJ']->getValorTotal()) . '</td>';
//                            echo '<td>' . number_format($venta['ventaOBJ']->getGanancia()) . '</td>';
                            echo '<td>' . $venta['ventaOBJ']->getFechaVenta() . '</td>';
                            echo '<td>';
//                            echo '<a href="" onclick="verEditar(' . $venta['ventaOBJ']->getPk_venta_id() . '); return false;" title="Editar esta Venta"><i class="fa fa-edit"></i></a>';
//                            echo '&nbsp;&nbsp;';
                            echo '<a href="" onclick="anexarArticulo(' . $venta['ventaOBJ']->getPk_venta_id() . '); return false;" title="Anexar articulos"><i class="fa fa-shopping-cart"></i></a>';
                            echo '&nbsp;&nbsp;';
                            echo '<a href="' . $this->url('administracion/default', array('controller' => 'venta', 'action' => 'imprimir', 'id1' => $venta['ventaOBJ']->getPk_venta_id())) . '" target="_blank" title="Generar PDF"><i class="fa fa-print"></i></a>';
//                            echo '&nbsp;&nbsp;';
//                             echo '<a href="" onclick="verDetalle(' . $venta['ventaOBJ']->getPk_venta_id() . '); return false;" title="Ver esta Venta a Detalle"><i class="fa fa-eye"></i></a>';
                            echo '&nbsp;&nbsp;';
                            echo '<a href="#" onclick="eliminar(' . $venta['ventaOBJ']->getPk_venta_id() . '); return false;" title="Eliminar esta Venta"><i class="fa fa-close"></i></a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Formulario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divContenido"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>POPGYM &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalAnexarProducto" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Seleccionar Producto</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divAnexarProducto"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>POPGYM. &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalAddProducto" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Cantidad a comprar</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">                               
                                <div class="x_content" id="divAddProducto"></div>
                                <div class="x_content" id="divContenido"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>POPGYM. &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div id="msgBloqueo" style="display: none;"> 
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE <i class="fa fa-spinner fa-spin fa-lg"></i>
</div>
<!-- PNotify -->
<script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.buttons.js'); ?>"></script>
<script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.nonblock.js'); ?>"></script>
