<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>Informacion de la Venta</legend> 
    <fieldset hidden><input id="incremental" name="incremental" value="1" class="form-control" readonly></fieldset>   
    <a class="btn btn-success" href="javascript:buscarProducto()"><i class="fa fa-plus-circle"></i> Agregar</a>
    <table id="tblCobros" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
            <tr>        
                <th title="ID"><i class="fa fa-key"></i></th>                                           
                <th title="NOMBRE"><i class="fa fa-list-alt"></i> NOMBRE</th>                                           
                <th title="PRECIO"><i class="fa fa-list-ol"></i> PRECIO</th>                                           
                <th title="CANTIDAD"><i class="fa fa-money"></i> CANTIDAD</th>
                <th title="MONTO"><i class="fa fa-money"></i> MONTO</th>             
                <th title="OPCIONES"><i class="fa fa-cog fa-spin fa-lg"></i></th> 
            </tr>                                    
        </thead>
        <tbody>
            <tr id="trInicial" style="background: #FFA">
                <td colspan="8">NO SE HAN AGREGADO PRODUCTOS <i class="fa fa-spinner fa-spin fa-lg"></i></td>
            </tr>
        </tbody>
        <tfoot>
        <td colspan="1" style=" border: inset 0pt"></td>
        <td colspan="1" style=" border: inset 0pt"></td>       
        <td colspan="1" style=" border: inset 0pt"></td>       
        <th style="background: #FFA">Total:</th>
        <th style="background: #FFA" id="total"></th>
        <td colspan="1" style=" border: inset 0pt"></td>
        </tfoot>
    </table>
</fieldset>
<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-close"></i> Cerrar</button>
        <button id="btnRegistrar" type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar</button>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
