<!-- footer content -->
<footer>
    <div class="row">
        <div class="col-xs-6 col-md-6" style="text-align: left">
            <!--<img src="<?php echo $this->basePath('public/img/logo.png') ?>" style="width: 150px" alt="Gimnasio - Jimmy Núñez Software e Ingenieria S.A.S."/>-->
        </div>
        <div class="col-xs-6 col-md-6" style="text-align: right">
            <b>SPARTANS</b><br>
            Jimmy90 &copy; Copyright <?php echo date(' Y') ?>
            
        </div>
    </div>
    <div class="clearfix"></div>
</footer>
<!-- /footer content -->
