<?php
$nombreUsuario = 'SESION NO INICIADA';
$titleNombreUsuario = 'SESION NO INICIADA';
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->nombreApellido);
    $foto = $this->escapeHtml($sesionUsuario->rutaFotoPerfil);
    $sexo = $this->escapeHtml($sesionUsuario->genero);
    $loginUsuario = $this->escapeHtml($sesionUsuario->login);
    $titleNombreUsuario = 'Has iniciado sesion como usuario ' . $loginUsuario;
}
?>
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav class="" role="navigation">
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="/gimnasio/public/img/profile/<?php echo $foto; ?>" alt=""><?php echo $nombreUsuario; ?>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="<?php echo $this->url('administracion/default', array('controller' => 'perfil', 'action' => 'index')) ?>"><i class="fa fa-user pull-right"></i><img src="/gimnasio/public/img/iconos/user.png"width="15" height="15"> Mi Perfíl</a></li>
                        <li><a href="javascript:;"><i class="fa fa-phone-square pull-right"></i><img src="/gimnasio/public/img/iconos/ayuda.png"width="15" height="15"> Ayuda</a></li>
                        <li><a href="<?php echo $this->url('login/default', array('controller' => 'login', 'action' => 'cerrarSesion')) ?>"><i class="fa fa-sign-out pull-right"></i><img src="/gimnasio/public/img/iconos/salir.png"width="15" height="15"> Salir</a></li>
                    </ul>
                </li>
                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">1</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image"><img src="/gimnasio/public/img/logo.png" alt="Profile Image" /></span>
                                <span>
                                    <span>PopGym</span>
                                    <span class="time">Hace 3 minutos</span>
                                </span>
                                <span class="message">
                                    Bienvenido <?php echo $nombreUsuario; ?> de parte de POPGYM ojalá nustra plataforma te sea de ayuda.
                                </span>
                            </a>
                        </li>
                </li>
                <li>
                    <div class="text-center">
                        <a>
                            <strong>Ver Todas Las Alertas</strong>
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </li>
            </ul>
            </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

