<?php
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/');
}

$nombreUsuario = 'SESION NO INICIADA';
$tipoUsuario = '2';
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->nombreApellido);
    $tipoUsuario = $this->escapeHtml($sesionUsuario->fk_rol_id);
    $sexo = $this->escapeHtml($sesionUsuario->genero);
    if ($sexo == 'Masculino') {
        $ao = 'o';
    } else {
        $ao = 'a';
    }
}

echo $this->doctype();
?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('.:: SPARTANS ::. ')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('build/css/custom.css'))
                ->prependStylesheet($this->basePath('vendors/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('vendors/bootstrap/dist/css/bootstrap.min.css'));
        echo $this->headScript()
                ->prependFile($this->basePath('vendors/jQuery-Smart-Wizard/js/jquery.smartWizard.js'))
                ->prependFile($this->basePath('vendors/nprogress/nprogress.js'))
                ->prependFile($this->basePath('vendors/fastclick/lib/fastclick.js'))
                ->prependFile($this->basePath('vendors/bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('vendors/jquery/dist/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <?php echo $this->header; ?>
                    <?php
                if ($tipoUsuario == '1') {
                    echo $this->menuadmin;
                } else if ($tipoUsuario == '2') {
                    echo $this->menu;
                } else if ($tipoUsuario == '3') {
                    echo $this->menuempleado;
                } else if ($tipoUsuario == '4') {
                    echo $this->menuinstructor;
                }
                ?>
                <div class="right_col" role="main">
                    <br />
                    <div class="">
                        <?php echo $this->content; ?>
                    </div>
                </div>
                <?php echo $this->footer; ?>
            </div>
        </div>
        <!-- Custom Theme Scripts -->
        <script src="/gimnasio/public/build/js/custom.js"></script>
        <script>
//----------------------------fullscreen----------------------------------------
            var elem = document.documentElement;
            function openFullscreen() {
                if (elem.requestFullscreen) {
                    elem.requestFullscreen();
                }
                if (document.exitFullscreen) {
                    document.exitFullscreen();
                }
            }
//------------------------------------------------------------------------------ 
        </script>
    </body>
</html>
