<?php
$nombreUsuario = 'SESION NO INICIADA';
$tipoUsuario = 'Usuario';
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->nombreApellido);
    $tipoUsuario = $this->escapeHtml($sesionUsuario->fk_rol_id);
    $foto = $this->escapeHtml($sesionUsuario->rutaFotoPerfil);
    $sexo = $this->escapeHtml($sesionUsuario->genero);

    if ($sexo == 'Masculino') {
        $ao = 'o';
    } else {
        $ao = 'a';
    }
}
?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title user-profile" style="border: 0;">
            <a href="#" class="site_title"><img src="/gimnasio/public/img/logo.png" alt="gimnasio"/> 
                <span>SPARTANS</span></a>
        </div>

        <div class="clearfix"></div>

 <!--<div style="text-align:center;padding:1em 0;"> <h6><a style="text-decoration:none;" href="https://www.zeitverschiebung.net/es/timezone/america--bogota"></a></h6> <iframe src="https://www.zeitverschiebung.net/clock-widget-iframe-v2?language=es&size=medium&timezone=America%2FBogota" width="100%" height="115" frameborder="0" seamless></iframe> </div>-->

        <div class="profile"><!--img_2 -->
            <div class="profile_pic">
                <img src="/gimnasio/public/img/profile/<?php echo $foto; ?>" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Bienvenid<?php echo $ao; ?>,</span>
                <h2><?php echo $nombreUsuario; ?></h2>
            </div>
        </div>
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <h3>Menu</h3>
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'index', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/home.png"width="30" height="30"> INICIO</a>
                    </li>                     
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'medidas', 'action' => 'indexMedidasUsuario')) ?>"><img src="/gimnasio/public/img/iconos/medidas.png"width="30" height="30"> Mis Medidas</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'rutinas', 'action' => 'indexRutinaUsuario')) ?>"><img src="/gimnasio/public/img/iconos/rutinas.png"width="30" height="30"> Mis Rutinas</a>
                    </li> 
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'mensualidad', 'action' => 'indexMensualidadUsuario')) ?>"><img src="/gimnasio/public/img/iconos/mensualidad.png"width="30" height="30"> Mi Mensualidad</a>
                    </li>                   
                </ul>
            </div>
        </div>

        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Configuracion">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Pantalla Completa" onclick="openFullscreen();">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Bloquear">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a href="<?php echo $this->url('login/default', array('controller' => 'login', 'action' => 'cerrarSesion')) ?>" data-toggle="tooltip" data-placement="top" title="Salir">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
    </div>
</div>








