<?php
$nombreUsuario = 'SESION NO INICIADA';
$tipoUsuario = '2';
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->nombreApellido);
    $tipoUsuario = $this->escapeHtml($sesionUsuario->fk_rol_id);
    $foto = $this->escapeHtml($sesionUsuario->rutaFotoPerfil);
    $sexo = $this->escapeHtml($sesionUsuario->genero);
    if ($sexo == 'Masculino') {
        $ao = 'o';
    } else {
        $ao = 'a';
    }
}
?>
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title user-profile" style="border: 0;">
            <a href="#" class="site_title"><img src="/gimnasio/public/img/logo.png" alt="gimnasio"/> 
                <span style="color:#edcb0a";>SPARTANS</span></a>
        </div>

        <div class="clearfix"></div>

 <!--<div style="text-align:center;padding:1em 0;"> <h6><a style="text-decoration:none;" href="https://www.zeitverschiebung.net/es/timezone/america--bogota"></a></h6> <iframe src="https://www.zeitverschiebung.net/clock-widget-iframe-v2?language=es&size=medium&timezone=America%2FBogota" width="100%" height="115" frameborder="0" seamless></iframe> </div>-->

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="/gimnasio/public/img/profile/<?php echo $foto; ?>" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Bienvenid<?php echo $ao; ?>,</span>
                <h2><?php echo $nombreUsuario; ?></h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menu General</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'index', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/home.png"width="30" height="30"> INICIO</a>
                    </li>                         
                    <li><a><img src="/gimnasio/public/img/iconos/usuarioRegistrado.png"width="30" height="30"> GESTION USUARIOS <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li>
                                <a href="<?php echo $this->url('administracion/default', array('controller' => 'usuario', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/user.png"width="30" height="30"> Accesos</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('administracion/default', array('controller' => 'clienteempleado', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/cliente.png"width="30" height="30">  Usuarios</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('administracion/default', array('controller' => 'rol', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/empleado.png"width="30" height="30">  Roles</a>
                            </li>                          
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'asistencia', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/asistencia.png"width="30" height="30"> ASISTENCIA</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'medidas', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/medidas.png"width="30" height="30"> MEDIDAS</a>
                    </li>
                    <li><a><img src="/gimnasio/public/img/iconos/rutinas.png"width="30" height="30"></i> RUTINAS <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li>
                                <a href="<?php echo $this->url('administracion/default', array('controller' => 'rutinas', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/crear.gif"width="30" height="30"> Crear Rutinas</a>
                            </li>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'usuariorutinas', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/asignar.gif"width="30" height="30"> Asignar Rutinas</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('administracion/default', array('controller' => 'ejercicios', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/ejercicio.gif"width="30" height="30"> Ejercicios</a>
                    </li>
                </ul>
                </li>
                <li><a><img src="/gimnasio/public/img/iconos/ingresos.png"width="30" height="30"> INGRESOS <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        <li>
                            <a href="<?php echo $this->url('administracion/default', array('controller' => 'mensualidad', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/mensualidad.png"width="25" height="25"> Mensualidad</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('administracion/default', array('controller' => 'entreno', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/entreno.png"width="25" height="25"> Entreno</a>
                        </li>
                        <li><a><img src="/gimnasio/public/img/iconos/shoppingCar.png"width="30" height="30"> Tienda <span class="fa fa-chevron-down"></span></a>
                            <ul class="nav child_menu">
                                <li>
                                    <a href="<?php echo $this->url('administracion/default', array('controller' => 'venta', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/vender.png"width="25" height="25"> Vender</a>
                                </li> 
                                <li>
                                    <a href="<?php echo $this->url('administracion/default', array('controller' => 'producto', 'action' => 'index')) ?>"><img src="/gimnasio/public/img/iconos/productos.png"width="25" height="25"> Productos</a>
                                </li>  
                            </ul>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('administracion/default', array('controller' => 'mensualidad', 'action' => 'indexReporteExcel')) ?>"><img src="/gimnasio/public/img/iconos/excel.png"width="25" height="25"> Reportes</a>
                        </li>
                    </ul>
                </li>
                </ul>
            </div>
        </div>

        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Configuracion">
                <span class="fa fa-cog fa-spin fa-lg" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Pantalla Completa" onclick="openFullscreen();">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Bloquear">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a href="<?php echo $this->url('login/default', array('controller' => 'login', 'action' => 'cerrarSesion')) ?>" data-toggle="tooltip" data-placement="top" title="Salir">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
    </div>
</div>
