<?php
$form = $this->form;
$form->prepare();
$hiddenInfoRegistro = '';
$action = $form->getAttribute('action');
if ($action == 'add') {
    $hiddenInfoRegistro = 'hidden';
}
echo $this->form()->openTag($form);
?>
<!--<fieldset <?php echo $hiddenInfoRegistro; ?>>
    <div class="form-group">
        <a class="btn btn-primary" onclick="cambiarClave()"><span class="fa fa-pencil-square-o"></span> Cambiar Clave</a>
    </div>

    <div id="divInfoUsuario" hidden></div>-->

</fieldset>
<fieldset>
    <legend>Informacion del usuario</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fk_clienteempleado_id">Usuario</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fk_clienteempleado_id')); ?>            
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fk_rol_id">Rol</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fk_rol_id')); ?>            
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="login">Login <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('login')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="password">Password <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="input-group">
                <?php echo $this->formRow($form->get('password')); ?>
                <span class="input-group-btn">
                    <button onmousedown="mostrarPassword(true)" onmouseup="mostrarPassword(false)" class="btn btn-default" type="button" title="Presionar para ver password"><span class="fa fa-eye"></span></button>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="passwordseguro">Confirmar Password <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="input-group">
                <?php echo $this->formRow($form->get('passwordseguro')); ?>
                <span class="input-group-btn">
                    <button onmousedown="mostrarPasswordConfirm(true)" onmouseup="mostrarPasswordConfirm(false)" class="btn btn-default" type="button" title="Presionar para ver password"><span class="fa fa-eye"></span></button>
                </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombreApellido">Nombres <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('nombreApellido')); ?>
            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="genero">SEXO</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('genero')); ?>
        </div>
    </div>
</fieldset>
<fieldset <?php echo $hiddenInfoRegistro; ?>>
    <legend>Informacion de Registro</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_usuario_id">ID</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pk_usuario_id')); ?>            
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="estado">ESTADO</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('estado')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="rutaFotoPerfil"><i class="fa fa-file-image-o"></i></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('rutaFotoPerfil')); ?>            
        </div>
    </div>
</fieldset>

<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <?php
        if ($action != 'buscar') {
            echo $this->formRow($form->get('btnCancelar'));
        }
        if ($action != 'detail' && $action != 'buscar') {
            echo $this->formSubmit($form->get('btnEnviar'));
        }
        ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
