<style>
    /*aca va el estilo de detalle*/

    .tblDetalles{
        background: #DDD;
        margin: 0 auto;
        width: 90%;
    }

    .tblDetalles td {
        padding: 0px 10px;
        border-bottom: 1px solid #FFF;
    }

    .detalleLabel {
        font-weight: bold;
        width: 30%;
    }

    .detalleTitulo {
        font-weight: bold;
        background: #333;
        color: #EEE;
        letter-spacing: 2px;
        height: 30px;
    }
</style>
<div id="divTxtDetalle">
    <table class="tblDetalles">
        <?php
        $usuario = $this->usuario;
        $simbolo = "";
        if ($usuario->getGenero() == 'Masculino') {
            $simbolo = 'fa fa-male';
        } else {
            $simbolo = 'fa fa-female';
        }


        echo
        '<tr>' .
        '<td class="detalleTitulo"><center>DATOS DEL USUARIO</center></td>' .
        '<td class="detalleTitulo" style="text-align: right"> Estado: ' . $usuario->getESTADO() . '</td>' .
        '</tr>' .
        '<tr>' .
        '<td class="detalleLabel">ID </td>' .
        '<td>' . $usuario->getPk_usuario_id() . '</td>' .
        '</tr>' .
        '<tr>' .
        '<td class="detalleLabel">ROL </td>' .
        '<td>' . $usuario->getFk_rol_id() . '</td>' .
        '</tr>' .
        '<tr>' .
        '<td class="detalleLabel">USUARIO </td>' .
        '<td>' . $usuario->getFk_clienteempleado_id() . '</td>' .
        '</tr>' .
        '<tr>' .
        '<td class="detalleLabel">NOMBRE </td>' .
        '<td>' . $usuario->getNombreApellido() . '</td>' .
        '</tr>' .
        '<tr>' .
        '<td class="detalleLabel">LOGIAN </td>' .
        '<td>' . $usuario->getLogin() . '</td>' .
        '</tr>' .
        '<tr>' .
        '<td class="detalleLabel">PASSWORD</td>' .
        '<td>' . $usuario->getPasswordseguro() . '</td>' .
        '</tr>' .
        '<tr>' .
        '<td class="detalleLabel">FOTO </td>' .
        '<td>' . $usuario->getRutaFotoPerfil() . ' <span style="float: right"><b>SEXO:  </b><i class="' . $simbolo . '"></i>' . '</span></td>' .
        '</tr>'
        ;
        ?>
    </table>
</div>
