<p class="text-muted font-13 m-b-30">
    A continuacion se listan todos los usuarios eliminados en el sistema.
    <button onclick="cargar();" class="btn btn-info">BUSCAR <i class="fa fa-search-plus"></i></button>
</p>
<table id="tblActivar" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>NOMBRES</th>
            <th>IDENTIFICACION</th>
            <th>TIPO USUARIO</th>
            <th></th>                                         
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->usuarios as $usuario) {
            echo '<tr>';
            echo '<td>' . $usuario['usuarioOBJ']->getPk_usuario_id() . '</td>';
            echo '<td>' . $usuario['usuarioOBJ']->getNombreApellido() . '</td>';
            echo '<td>' . $usuario['clienteempleadoOBJ']->getIdentificacion() . '</td>';
            echo '<td>' . $usuario['rolOBJ']->getRol() . '</td>';
            echo '<td>';
            echo '<a href="" onclick="activarUsuario(' . $usuario['usuarioOBJ']->getPk_usuario_id() . '); return false;" title="Activar usuario"><i class="fa fa-lightbulb-o"></i></a>';
            echo '</td>';
            echo '</tr>';
        }
        ?>
    </tbody>
</table>
<script>
    function cargar() {
        $("#tblActivar").DataTable({
            responsive: true,
            "iDisplayLength": 25,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                "sInfoEmpty": "Mostrando 0 A 0 registros",
                "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                "sLoadingRecords": "CARGANDO...",
                "sProcessing": "EN PROCESO...",
                "sSearch": "Buscar:",
                "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                "oPaginate": {
                    "sFirst": "Inicio",
                    "sLast": "Fin",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                }
            },
            "aaSorting": [[0, "des"]]
        });
    }
</script>