<legend><b><i class="fa fa-paw"></i> Huella dactilar de:</b> <?php echo $this->imgHuella['nombreUsuario']; ?></legend>
<div align="center">
    <img src="data:image/png;base64, <?php echo $this->imgHuella['imgHuella']; ?>" style="border: 15px solid; color:#EDCB0A;" alt="Huella no registrada">
</div>
<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-close"></i> Cerrar</button>
    </div>
</div>
