<!DOCTYPE html>
<html lang="en">
    <!-- page content -->

    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Usuarios <small>POPGYM</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="<?php echo $this->url('administracion/default', array('controller' => 'perfil', 'action' => 'index')) ?>"><i class="fa fa-user"></i> Mi Perfil</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                            <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                                <ul class="pagination pagination-split">
                                    <li><a href="#">A</a></li>
                                    <li><a href="#">B</a></li>
                                    <li><a href="#">C</a></li>
                                    <li><a href="#">D</a></li>
                                    <li><a href="#">E</a></li>
                                    <li>...</li>
                                    <li><a href="#">W</a></li>
                                    <li><a href="#">X</a></li>
                                    <li><a href="#">Y</a></li>
                                    <li><a href="#">Z</a></li>
                                </ul>
                            </div>

                            <div class="clearfix"></div>
                            <!--perfil-->
                            <?php
                            foreach ($this->usuarios as $usuario) {
                                echo '<div class="col-md-4 col-sm-4 col-xs-12 profile_details">';
                                echo '<div class="well profile_view">';
                                echo '<div class = "col-sm-12">';
                                echo '<h4 class = "brief"><i>ID: ' . $usuario->getPk_clienteempleado_id() . '</i></h4>';
                                echo '<div class = "left col-xs-7">';
                                echo '<h2>' . $usuario->getNombre() . ' ' . $usuario->getApellido() . '</h2 > ';
                                echo '<p><strong>Ocupacion: </strong>' . $usuario->getOcupacion() . ' </p>';
                                echo '<ul class = "list-unstyled">';
                                echo '<li><i class = "fa fa-building"></i> Direccion: ' . $usuario->getDireccion() . '</li>';
                                echo '<li><i class = "fa fa-phone"></i> Phone #: ' . $usuario->getTelefono() . '</li>';
                                echo '</ul>
                                </div>
                                <div class = "right col-xs-5 text-center">';
                                echo '<img src = "/public/img/profile/' . $usuario->getRutaFotoPerfil() . '" alt = "" class = "img-circle img-responsive">';
                                echo '</div>
                                </div>

                                <div class = "col-xs-12 bottom text-center">
                                <div class = "col-xs-12 col-sm-6 emphasis">
                                <p class = "ratings">
                                <a>4.0</a>
                                <a href = "#"><span class = "fa fa-star"></span></a>
                                <a href = "#"><span class = "fa fa-star"></span></a>
                                <a href = "#"><span class = "fa fa-star"></span></a>
                                <a href = "#"><span class = "fa fa-star"></span></a>
                                <a href = "#"><span class = "fa fa-star-o"></span></a>
                                </p>
                                </div>
                                <div class = "col-xs-12 col-sm-6 emphasis">
                                <button id="compose" type = "button" class = "btn btn-success btn-xs" title="Enviar Mensaje"> <i class = "fa fa-user">
                                </i> <i class = "fa fa-comments-o"></i> </button>
                                <button type = "button" class = "btn btn-primary btn-xs">
                                <i class = "fa fa-user"> </i> View Profile
                                </button>
                                </div>
                                </div>
                                </div>
                                </div>';
                            }
                            ?>
                            <!--/perfil-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

    <!-- compose -->
    <div class="compose col-md-6 col-xs-12">
        <div class="compose-header">
            Nuevo Mensaje
            <button type="button" class="close compose-close">
                <span>×</span>
            </button>
        </div>

        <div class="compose-body">
            <div id="alerts"></div>

            <div class="btn-toolbar editor" data-role="editor-toolbar" data-target="#editor">
                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="fa fa-font"></i><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                    </ul>
                </div>

                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="fa fa-text-height"></i>&nbsp;<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a data-edit="fontSize 5">
                                <p style="font-size:17px">Huge</p>
                            </a>
                        </li>
                        <li>
                            <a data-edit="fontSize 3">
                                <p style="font-size:14px">Normal</p>
                            </a>
                        </li>
                        <li>
                            <a data-edit="fontSize 1">
                                <p style="font-size:11px">Small</p>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="btn-group">
                    <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
                    <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
                    <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
                    <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
                </div>

                <div class="btn-group">
                    <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="fa fa-list-ul"></i></a>
                    <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="fa fa-list-ol"></i></a>
                    <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="fa fa-dedent"></i></a>
                    <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="fa fa-indent"></i></a>
                </div>

                <div class="btn-group">
                    <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
                    <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="fa fa-align-center"></i></a>
                    <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="fa fa-align-right"></i></a>
                    <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="fa fa-align-justify"></i></a>
                </div>

                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="fa fa-link"></i></a>
                    <div class="dropdown-menu input-append">
                        <input class="span2" placeholder="URL" type="text" data-edit="createLink" />
                        <button class="btn" type="button">Add</button>
                    </div>
                    <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="fa fa-cut"></i></a>
                </div>

                <div class="btn-group">
                    <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="fa fa-picture-o"></i></a>
                    <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" />
                </div>

                <div class="btn-group">
                    <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="fa fa-undo"></i></a>
                    <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="fa fa-repeat"></i></a>
                </div>
            </div>

            <div id="editor" class="editor-wrapper"></div>
        </div>

        <div class="compose-footer">
            <button id="send" class="btn btn-sm btn-success" type="button">Enviar</button>
        </div>
    </div>
    <!-- /compose -->
    <!-- bootstrap-wysiwyg -->
    <script src="/public/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
    <script src="/public/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
    <script src="/public/vendors/google-code-prettify/src/prettify.js"></script>

    <script>
        /* COMPOSE */
        function init_compose() {

            if (typeof ($.fn.slideToggle) === 'undefined') {
                return;
            }
            console.log('init_compose');

            $('#compose, .compose-close').click(function () {
                $('.compose').slideToggle();
            });

        }
        /* WYSIWYG EDITOR */
        function init_wysiwyg() {

            if (typeof ($.fn.wysiwyg) === 'undefined') {
                return;
            }
            console.log('init_wysiwyg');

            function init_ToolbarBootstrapBindings() {
                var fonts = ['Serif', 'Sans', 'Arial', 'Arial Black', 'Courier',
                    'Courier New', 'Comic Sans MS', 'Helvetica', 'Impact', 'Lucida Grande', 'Lucida Sans', 'Tahoma', 'Times',
                    'Times New Roman', 'Verdana'
                ],
                        fontTarget = $('[title=Font]').siblings('.dropdown-menu');
                $.each(fonts, function (idx, fontName) {
                    fontTarget.append($('<li><a data-edit="fontName ' + fontName + '" style="font-family:\'' + fontName + '\'">' + fontName + '</a></li>'));
                });
                $('a[title]').tooltip({
                    container: 'body'
                });
                $('.dropdown-menu input').click(function () {
                    return false;
                })
                        .change(function () {
                            $(this).parent('.dropdown-menu').siblings('.dropdown-toggle').dropdown('toggle');
                        })
                        .keydown('esc', function () {
                            this.value = '';
                            $(this).change();
                        });

                $('[data-role=magic-overlay]').each(function () {
                    var overlay = $(this),
                            target = $(overlay.data('target'));
                    overlay.css('opacity', 0).css('position', 'absolute').offset(target.offset()).width(target.outerWidth()).height(target.outerHeight());
                });

                if ("onwebkitspeechchange" in document.createElement("input")) {
                    var editorOffset = $('#editor').offset();

                    $('.voiceBtn').css('position', 'absolute').offset({
                        top: editorOffset.top,
                        left: editorOffset.left + $('#editor').innerWidth() - 35
                    });
                } else {
                    $('.voiceBtn').hide();
                }
            }

            function showErrorAlert(reason, detail) {
                var msg = '';
                if (reason === 'unsupported-file-type') {
                    msg = "Unsupported format " + detail;
                } else {
                    console.log("error uploading file", reason, detail);
                }
                $('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>' +
                        '<strong>File upload error</strong> ' + msg + ' </div>').prependTo('#alerts');
            }

            $('.editor-wrapper').each(function () {
                var id = $(this).attr('id');	//editor-one

                $(this).wysiwyg({
                    toolbarSelector: '[data-target="#' + id + '"]',
                    fileUploadError: showErrorAlert
                });
            });


            window.prettyPrint;
            prettyPrint();

        }
        $(document).ready(function () {
            init_wysiwyg();
            init_compose();
        });
    </script>
</body>
</html>