<?php 
$title = 'medidas';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('/public/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/green.css'));

$this->headScript()->prependScript('$(document).ready(function() {'
                . '$("#tblRutinass").DataTable({'
                . 'responsive: true,'
                . '"iDisplayLength": 25,
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                        "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                        "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        "sInfoEmpty": "Mostrando 0 A 0 registros",
                        "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                        "sLoadingRecords": "CARGANDO...",
                        "sProcessing": "EN PROCESO...",
                        "sSearch": "Buscar:",
                        "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        "oPaginate": {
                            "sFirst": "Inicio",
                            "sLast": "Fin",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        }
                    },
                    "aaSorting": [[0, "asc"]]'
                . '});'
                . '});'
                , 'text/javascript'
                , array('noescape' => true))
        ->prependFile('/gimnasio/public/js/sistema/medidas.js')
        ->prependFile('/gimnasio/public/js/datatables.scroller.min.js')
        ->prependFile('/gimnasio/public/js/responsive.bootstrap.js')
        ->prependFile('/gimnasio/public/js/dataTables.responsive.min.js')
        ->prependFile('/gimnasio/public/js/buttons.bootstrap.min.js')
        ->prependFile('/gimnasio/public/js/dataTables.buttons.min.js')
        ->prependFile('/gimnasio/public/js/dataTables.bootstrap.min.js')
        ->prependFile('/gimnasio/public/js/jquery.dataTables.min.js');
$formRutinas = $this->form;
?>
<div class="page-title">
    <div class="title_left">
        <h3><i class="fa fa-file-text"></i> Rutinas <small>ANEXAR Usuario</small></h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">IR!</button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row" style="min-height: 1000px">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Anexar Ejercicios <small>RUTINAS</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>    
                        <button type="button" onclick="seleccionarUsuario(<?php echo $formRutinas->get('pk_medida_id')->getValue(); ?>)" class="btn btn-success"><i class="fa fa-plus"></i> Anexar Ejercicio</button>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br>
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos las ejercicioss anexadas a este cuestionario.
                </p>
             <table id="tblMedidas" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>ID Medidas</th>
                            <th>Usuario</th>
                            <th>Fecha</th>
                            <th>Estatura</th>
                            <th>Peso</th>                           
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->medidas as $medida) {
                            echo '<tr>';
                            echo '<td>' . $medida->getPk_medida_id() . '</td>';
                            echo '<td>' . $medida->getOBJ_USU()->getNOM_USU() . ' ' . $medida->getOBJ_USU()->getAPELL_USU() . '</td>';
                            echo '<td>' . $medida->getFECHA_MED_USU() . '</td>';
                            echo '<td>' . $medida->getESTATURA() . '</td>';
                            echo '<td>' . $medida->getPESO() . '</td>';

                            echo '<td>';
                            echo '<a href="" onclick="verEditar(' . $medida->getPk_medida_id() . '); return false;" title="Editar este Medidas"><i class="fa fa-edit"></i></a>';
                            echo '&nbsp;&nbsp;';
                            echo '<a href="" onclick="verDetalle(' . $medida->getPk_medida_id() . '); return false;" title="Ver este Medidas a Detalle"><i class="fa fa-eye"></i></a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                </table>
                <div class="ln_solid"></div>
                <?php
                $formRutinas->prepare();
                echo $this->form()->openTag($formRutinas);
                ?>
                <fieldset>
                    <legend>Informacion del Rutinas</legend>
                    
                    
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fk_usuario_id">ID Uusario <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($formRutinas->get('fk_usuario_id')); ?>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Informacion de Registro</legend>
                    
                    
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fk_usuario_id">Uusario</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <?php echo $this->formRow($formRutinas->get('fk_usuario_id')); ?>
                        </div>
                    </div>
                    
                    
                    
                </fieldset>
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                        <?php
                        echo $this->formRow($formRutinas->get('btnCancelar'));
                        ?>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalAnexarUsuario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Seleccionar Ejercicio</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divAnexarUsuario"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>PsicoTest &copy Copyright <?php echo date('Y/M/D'); ?></b>
            </div>
        </div>
    </div>
</div>
