<?php
//--------- CARGAR MENSAJES DE ALERTA ------------------------------------------
//$formBusquedas = $this->formBusquedas;
$flash = $this->flashMessenger();
$notificaciones = [
    'success' => array_merge($flash->getSuccessMessages(), $flash->getCurrentSuccessMessages()),
    'error' => array_merge($flash->getErrorMessages(), $flash->getCurrentErrorMessages()),
    'alert' => array_merge($flash->getMessages(), $flash->getCurrentMessages()),
    'information' => array_merge($flash->getInfoMessages(), $flash->getCurrentInfoMessages()),
    'warning' => array_merge($flash->getWarningMessages(), $flash->getCurrentWarningMessages()),
];
$flash->clearCurrentMessages('default');
$flash->clearCurrentMessages('info');
$flash->clearCurrentMessages('success');
$flash->clearCurrentMessages('warning');
$flash->clearCurrentMessages('error');
$mensaje = 'EJERCICIOS';
$tipo = 'info';
foreach (array_filter($notificaciones) as $tipo => $mensajes) {
    foreach ($mensajes as $mensaje) {
        
    }
}
//------------------------------------------------------------------------------
$title = 'Ejercicioss ';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.buttons.css'))
        ->prependStylesheet($this->basePath('vendors/pnotify/dist/pnotify.nonblock.css'))
        ->prependStylesheet($this->basePath('css/sweetalert2.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'));

$this->headScript()->prependScript('
                $(document).ajaxStop($.unblockUI); 
                $(document).ready(function() {
                     $("#tblEjercicioss").DataTable({
                        "responsive": "true",
                        "iDisplayLength": 25,
                        "sPaginationType": "full_numbers",
                        "oLanguage": {
                            "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                            "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                            "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                            "sInfoEmpty": "Mostrando 0 A 0 registros",
                            "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                            "sLoadingRecords": "CARGANDO...",
                            "sProcessing": "EN PROCESO...",
                            "sSearch": "Buscar:",
                            "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                            "oPaginate": {
                                "sFirst": "Inicio",
                                "sLast": "Fin",
                                "sNext": "Siguiente",
                                "sPrevious": "Anterior"
                            }
                        },
                        "aaSorting": [[0, "des"]]
                });
                    //------------------------------------------------------------------------------
                    // MANIPULACION DEL EVENTO DE CIERRE DEL MODAL
                    //------------------------------------------------------------------------------
                    $("#modalFormulario").on("hide.bs.modal", function (e) {
                        return confirmarCerrar();
                    }); 
                    new PNotify({
                     title: "<br>SPARTANS<br>",
                     text: "' . $mensaje . '",
                     type: "' . $tipo . '",
                     styling: "bootstrap3"
                    });
       });', 'text/javascript', array('noescape' => true))
        ->prependFile('/public/js/sistema/ejercicios.js')
        ->prependFile($this->basePath('js/jquery.blockUI.js'))
        ->prependFile('/public/vendors/iCheck/icheck.min.js')
        ->prependFile('/public/vendors/datatables.net-scroller/js/dataTables.scroller.min.js')
        ->prependFile('/public/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')
        ->prependFile('/public/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')
        ->prependFile('/public/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons/js/buttons.html5.min.js')
        ->prependFile('/public/vendors/datatables.net-buttons/js/buttons.print.min.js')
        ->prependFile('/public/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')
        ->prependFile('/public/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')
        ->prependFile('/public/vendors/pdfmake/build/pdfmake.min.js')
        ->prependFile('/public/vendors/pdfmake/build/vfs_fonts.js')
        ->prependFile($this->basePath('vendors/pnotify/dist/pnotify.js'))
        ->prependFile($this->basePath('js/SwtSistema.js'))
        ->prependFile($this->basePath('js/sweetalert2.all.min2021.js'))
        ->prependFile('/public/vendors/datatables.net/js/jquery.dataTables.min.js');
?>
<div class="page-title">
    <div class="title_left">
        <h3><i class="fa fa-file-text"></i> Ejercicios <small>PRINCIPAL</small></h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">IR!</button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Registros del Sistema <small>Ejercicios</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>    
                        <button type="button" onclick="verAgregarEjercicios()" class="btn btn-success"><i class="fa fa-plus"></i> Registrar Ejercicios</button>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos los ejercicios registrados en el sistema.
                </p>
                <table id="tblEjercicioss" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Zona Muscular</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->ejercicioss as $ejercicios) {
                            echo '<tr>';
                            echo '<td>' . $ejercicios->getPk_ejercicio_id() . '</td>';
                            echo '<td>' . $ejercicios->getNOM_EJER() . '</td>';
                            echo '<td>' . $ejercicios->getZonaMuscular() . '</td>';
                            echo '<td>';
                            echo '<a href="" onclick="verEditar(' . $ejercicios->getPk_ejercicio_id() . '); return false;" title="Editar este Medidas"><i class="fa fa-edit"></i></a>';
                            echo '&nbsp;&nbsp;';
                            echo '<a href="" onclick="detalleEjercicio(' . $ejercicios->getPk_ejercicio_id() . '); return false;" title="Ver este Medidas a Detalle"><i class="fa fa-eye"></i></a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Formulario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divContenido"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>POPGYM &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="dlgDetalles" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                <img src="/public/img/logo.png" style="width: 8%" alt="Gimnasio"/>
                <h4 class="modal-title">POPGYM</h4>
            </div>
            <div class="modal-body" >
                <div id="divDetalle" class="row"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
            <div class="modal-footer">
                <b>POPGYM &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div id="msgBloqueo" style="display: none;"> 
    SU SOLICITUD ESTA SIENDO PROCESADA, POR FAVOR ESPERE <i class="fa fa-spinner fa-spin fa-lg"></i>
</div>
<script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.buttons.js'); ?>"></script>
<script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.nonblock.js'); ?>"></script>

