<p class="text-muted font-13 m-b-30">
    A continuacion se listan todas las ejercicioss registradas en el sistema que no han sido anexadas al actual rutina.
</p><br>
<table id="tblSeleccionarEjercicios" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Zona Muscular</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->ejercicios as $ejercicio) {
            echo '<tr>';
            echo '<td>' . $ejercicio->getPk_ejercicio_id() . '</td>';
            echo '<td>' . $ejercicio->getNOM_EJER() . '</td>';
            echo '<td>' . $ejercicio->getZonaMuscular() . '</td>';
            echo '<td>';
            echo '<a href="" onclick="detalleEjercicio(' . $ejercicio->getPk_ejercicio_id() . '); return false;" title="Ver Este Ejercicio"><i class="fa fa-file-image-o"></i></a>';
            echo '&nbsp;&nbsp;';
            echo '<a href="" onclick="setInfoEjercicio(' . $ejercicio->getPk_ejercicio_id() . '); return false;" title="Seleccionar esta Ejercicios"><i class="fa fa-check"></i></a>';
            echo '</td>';
            echo '</tr>';
        }
        ?>
    </tbody>
</table>
