<?php
$form = $this->form;
$form->prepare();
$hiddenInfoRegistro = '';
$action = $form->getAttribute('action');
if ($action == 'add') {
    $hiddenInfoRegistro = 'hidden';
}
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>Informacion de la  Mensualidad</legend>
    <div class="form-group">
        <a class="btn btn-primary" onclick="seleccionarUsuario()"><span class="fa fa-search"></span> Buscar Usuario</a>
    </div>

    <div id="divInfoUsuario" hidden></div>

</fieldset>
<fieldset>
    <legend>Informacion de la mensualidad</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="FECHA_MENS">Fecha de Inicio <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('FECHA_MENS')); ?>
        </div>
    </div> 
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="FECHA_MENS_FIN">Fecha Final <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('FECHA_MENS_FIN')); ?>
        </div>
    </div> 
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="valor">Valor $:<span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('valor')); ?>
        </div>
    </div> 
</fieldset>

<fieldset <?php echo $hiddenInfoRegistro; ?>>
    <legend>Informacion de Registro</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_mensualidad_id">ID Mensualidad</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pk_mensualidad_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fk_usuario_id">ID Usuario</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fk_usuario_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechaUltPreaviso">Fecha Preaviso</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechaUltPreaviso')); ?>
        </div>
    </div>
</fieldset>

<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <?php
        if ($action != 'buscar') {
            echo $this->formRow($form->get('btnCancelar'));
        }
        if ($action != 'detail' && $action != 'buscar') {
            echo $this->formSubmit($form->get('btnEnviar'));
        }
        ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
