<?php
$title = 'Mensualidades ';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'));

$this->headScript()->prependScript('$(document).ready(function() {'
                . '$("#tblMensualidades").DataTable({'
                . 'responsive: true,'
                . '"iDisplayLength": 25,
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                        "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                        "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        "sInfoEmpty": "Mostrando 0 A 0 registros",
                        "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                        "sLoadingRecords": "CARGANDO...",
                        "sProcessing": "EN PROCESO...",
                        "sSearch": "Buscar:",
                        "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        "oPaginate": {
                            "sFirst": "Inicio",
                            "sLast": "Fin",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        }
                    },
                    "aaSorting": [[0, "des"]]'
                . '});'
                . '});'
                , 'text/javascript'
                , array('noescape' => true))
        ->prependFile($this->basePath('js/sistema/mensualidad.js'))
        ->prependFile($this->basePath('vendors/iCheck/icheck.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-scroller/js/dataTables.scroller.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'))
        ->prependFile($this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'))
        ->prependFile($this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/pdfmake.min.js'))
        ->prependFile($this->basePath('vendors/pdfmake/build/vfs_fonts.js'))
        ->prependFile($this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'));
?>
<div class="page-title">
    <div class="title_left">
        <h3><i class="fa fa-file-text"></i> Mensualidad <small>PRINCIPAL</small></h3>
    </div>
    <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Buscar...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">IR!</button>
                </span>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Registros del Sistema <small>Mensualidad</small></h2>
                <!--                <ul class="nav navbar-right panel_toolbox">
                                    <li>    
                                        <button type="button" onclick="verAgregarMensualidad()" class="btn btn-success"><i class="fa fa-plus"></i> Registrar Mensualidad</button>                    
                                        <button type="button" onclick="enviarPreaviso()" class="btn btn-success"><i class="fa fa-envelope"></i> Enviar Preaviso</button>
                                    </li>
                                </ul>-->
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos los mensualidades registrados en el sistema.
                </p>
                <table id="tblMensualidades" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Usuario</th>   
                            <th>FechaInicio</th>
                            <th>FechaFinal</th>
                            <th>Dias Faltantes</th>
                            <!--<th></th>-->
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->mensualidades as $mensualidad) {
                            $estiloDiasFal = "";
                            $estiloPreaviso = "";
                            if ($mensualidad['enivarPreaviso'] <= '0000-00-00 00:00:00') {
                                $estiloPreaviso = 'style="background: #FAA"'; //rojo
                            } else {
                                $estiloPreaviso = 'style="background: #AFA"'; //verde
                            }
                            if ($mensualidad['diasPreaviso'] >= 4) {
                                $estiloDiasFal = 'style="background: #AFA"'; //verde
                            } elseif ($mensualidad['diasPreaviso'] <= 3 && $mensualidad['diasPreaviso'] >= 0) {
                                $estiloDiasFal = 'style="background: #FFA"'; //Amarillo
                            } elseif ($mensualidad['diasPreaviso'] < 0) {
                                $estiloDiasFal = 'style="background: #FAA"'; //Rojo
                            }
                            echo '<tr>';
                            echo '<td>' . $mensualidad['mensualidadOBJ']->getPk_mensualidad_id() . '</td>';
                            echo '<td>' . $mensualidad['usuarioOBJ']->getNombreApellido() . '</td>';
                            echo '<td>' . $mensualidad['mensualidadOBJ']->getFECHA_MENS() . '</td>';
                            echo '<td>' . $mensualidad['mensualidadOBJ']->getFECHA_MENS_FIN() . '</td>';
                            echo '<td ' . $estiloDiasFal . 'title="Dias Faltantes">' . $mensualidad['diasPreaviso'] . '</td>';
//                            echo '<td ' . $estiloPreaviso . 'title="Enviar Preaviso">';
//                            echo '<input type="checkbox" value="' . $mensualidad['mensualidadOBJ']->getPk_mensualidad_id() . '">';
//                            echo '</td>';
                            echo '<td>';
//                            echo '<a href="" onclick="verEditar(' . $mensualidad['mensualidadOBJ']->getPk_mensualidad_id() . '); return false;" title="Renovar esta Mensualidad"><i class="fa fa-edit"></i></a>';
//                            echo '&nbsp;&nbsp;';
                            echo '<a href="" onclick="verDetalle(' . $mensualidad['mensualidadOBJ']->getPk_mensualidad_id() . '); return false;" title="Ver esta Mensualidad a Detalle"><i class="fa fa-eye"></i></a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                </table>
            </div>
        </div>
    </div>
</div>

<form hidden id='frmEnviarPreaviso' method="post" action="<?php echo $this->url('administracion/default', array('controller' => 'mensualidad', 'action' => 'enviarPreaviso')) ?>">
    <input type="text" name="idsMensualidades" id='idsMensualidades' value="">
</form>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Formulario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divContenido"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>Gimnasio &copy Copyright <?php echo date('Y/M/d'); ?></b>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalAnexarUsuario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Seleccionar Usuario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divAnexarUsuario"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>PsicoTest &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>

