<?php
$form = $this->form;
$form->prepare();
$hiddenInfoRegistro = '';
$action = $form->getAttribute('action');
if ($action == 'add') {
    $hiddenInfoRegistro = 'hidden';
}
echo $this->form()->openTag($form);
?>
<fieldset>
    <legend>Informacion del usuario</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="nombre">Nombre <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('nombre')); ?>
            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="apellido">Apellido <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('apellido')); ?>
            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="tipoIdentificacion">Tipo Iden.. <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('tipoIdentificacion')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="identificacion">Identificacion <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('identificacion')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechaNacimiento">Fecha Nacimiento <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('fechaNacimiento')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="ocupacion">Ocupacion <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('ocupacion')); ?>
            <span class="fa fa-briefcase form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Correo <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('email')); ?>
            <span class="fa fa-external-link-square form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="telefono">Telefono <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('telefono')); ?>
            <span class="fa fa-phone-square form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="direccion">Direccion <span class="required">*</span></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('direccion')); ?>
            <span class="fa fa-external-link form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="genero">Genero</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('genero')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="condicionFisica">condicion Fisica</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('condicionFisica')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="OBJETIVOS">Objetivos</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('OBJETIVOS')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="estado">Estado</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('estado')); ?>
        </div>
    </div>
</fieldset>
<fieldset <?php echo $hiddenInfoRegistro; ?>>
    <legend>Informacion de Registro</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_clienteempleado_id"><i class="fa fa-key"></i></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('pk_clienteempleado_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="rutaFotoPerfil"><i class="fa fa-photo"></i></label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($form->get('rutaFotoPerfil')); ?>
            <span class="fa fa-photo form-control-feedback left" aria-hidden="true"></span>
        </div>
    </div>
</fieldset>

<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <?php
        if ($action != 'buscar') {
            echo $this->formRow($form->get('btnCancelar'));
        }
        if ($action != 'detail' && $action != 'buscar') {
            echo $this->formSubmit($form->get('btnEnviar'));
        }
        ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
