<br><br><br>
<div class="col-md-12 col-sm-12 col-xs-12">
    <section id="hero">
        <div class="x_content">

            <div class="bs-example" data-example-id="simple-jumbotron">
                <div class="">
                    <h1 style="text-align: center;
                        font-size: 66px; 
                        font-weight: 600;
                        line-height: 200px;">POPGYM</h1>
                    <p style="
                       text-align: center;
                       font-size: 18px;                      
                       line-height: 1.8;
                       margin-bottom: 0;">Confía en el proceso y los resultados llegarán.</p>
                </div>
            </div>

        </div>
    </section>
    <br><br>
</div>

<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio2.jpg" alt="image" />
            <div class="mask">
                <p>Your Text</p>
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p>Snow and Ice Incoming for the South</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio3.jpg" alt="image" />
            <div class="mask">
                <p>Your Text</p>
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p>Snow and Ice Incoming for the South</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio4.jpg" alt="image" />
            <div class="mask">
                <p>Your Text</p>
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p>Snow and Ice Incoming for the South</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio5.jpg" alt="image" />
            <div class="mask">
                <p>Your Text</p>
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p>Snow and Ice Incoming for the South</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio6.jpg" alt="image" />
            <div class="mask">
                <p>Your Text</p>
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p>Snow and Ice Incoming for the South</p>
        </div>
    </div>
</div>


<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio7.jpg" alt="image" />
            <div class="mask no-caption">
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p><strong>Image Name</strong>
            </p>
            <p>Snow and Ice Incoming</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio8.jpg" alt="image" />
            <div class="mask no-caption">
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p><strong>Image Name</strong>
            </p>
            <p>Snow and Ice Incoming</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio9.jpg" alt="image" />
            <div class="mask no-caption">
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p><strong>Image Name</strong>
            </p>
            <p>Snow and Ice Incoming</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio10.jpg" alt="image" />
            <div class="mask no-caption">
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p><strong>Image Name</strong>
            </p>
            <p>Snow and Ice Incoming</p>
        </div>
    </div>
</div>
<div class="col-md-55">
    <div class="thumbnail">
        <div class="image view view-first">
            <img style="width: 100%; display: block;" src="/public/img/gimnasio11.jpg" alt="image" />
            <div class="mask no-caption">
                <div class="tools tools-bottom">
                    <a href="#"><i class="fa fa-link"></i></a>
                    <a href="#"><i class="fa fa-pencil"></i></a>
                    <a href="#"><i class="fa fa-times"></i></a>
                </div>
            </div>
        </div>
        <div class="caption">
            <p><strong>Image Name</strong>
            </p>
            <p>Snow and Ice Incoming</p>
        </div>
    </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_content">
            <ul class="list-unstyled timeline">
                <li>
                    <div class="block">
                        <div class="tags">
                            <a href="" class="tag">
                                <span>MISIÓN</span>
                            </a>
                        </div>
                        <div class="block_content">
                            <h2 class="title">
                                <a>MISIÓN</a>
                            </h2>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Contribuir al desarrollo integral de los clientes mediante el diseño y la aplicación de un conjunto de servicios que fortalezcan la salud física y mental.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Ayudar a nuestros socios a crear y mantener una excelente condición física a través de la nutrición y programas de entrenamiento.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Inculcar en niños, jóvenes y adultos, el valor de la salud y el ejercicio.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Mejorar la calidad de vida de las comunidades a través de la filosofía del ejercicio, programas y productos de nutrición.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Participar proactivamente en el bienestar de las personas en su entorno social y laboral.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Brindar un servicio único y facilitar las herramientas del éxito.
                            </p>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="block">
                        <div class="tags">
                            <a href="" class="tag">
                                <span>VISIÓN</span>
                            </a>
                        </div>
                        <div class="block_content">
                            <h2 class="title">
                                <a>VISIÓN</a>
                            </h2>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Ser un gimnasio líder, brindando calidad y bienestar a nuestros miembros, generando valor humano y profesional a nuestra empresa, a nuestros colaboradores y a nuestra comunidad.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Ser la mejor opción deportiva en la ciudad de <b>Popayán</b>, por la excelencia en los servicios y la moderna aparatología, potenciando los procesos de servicio al cliente y la atención personalizada.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Ofrecer un ambiente ameno, accesible, práctico y estimulante, en el que todo socio pueda expresar su competencia física, mental y espiritual.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Optimizar los objetivos de captación y retención de socios, garantizando calidad y resultados tangibles.
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Promover la integración familiar por medio de las actividades deportivas en un clima sano, alegre y positivo.
                            </p>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="block">
                        <div class="tags">
                            <a href="" class="tag">
                                <span>VALORES</span>
                            </a>
                        </div>
                        <div class="block_content">
                            <h2 class="title">
                                <a>VALORES</a>
                            </h2>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Apego a la filosofía de la salud y el bienestar
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Profesionalismo
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Eficacia en el logro de los objetivos
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Eficacia en el uso de los recursos
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Excelencia en servicios
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Compromiso social
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Compromiso ambiental
                            </p>
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Comportamiento ético y moral
                            </p>  
                            <p class="excerpt"><i class="fa fa-check-circle"></i>Respeto a la integridad de nuestros usuarios, empleados y proveedores.
                            </p>  
                        </div>
                    </div>
                </li>
            </ul>

        </div>
    </div>
</div>
<!-- footer content -->
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="pull-right">

        <div class="flex">
            <ul class="list-inline ">               
                <li>
                    <a title="Facebook" href="https://www.facebook.com/">
                        <i class="fa fa-facebook"></i>
                    </a>
                </li>                
                <li>
                    <a title="Twitter" href="https://twitter.com/?lang=es">
                        <i class="fa fa-twitter"></i>
                    </a>
                </li>
                <li>
                    <a title="Instagram" href="https://www.instagram.com/?hl=es-la">
                        <i class="fa fa-instagram"></i>
                    </a>
                </li>
                <li>
                    <h4><span class="label label-primary">POPGYM</span></h4>
                </li>
            </ul>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

<!-- /footer content -->