<?php
$formRutinas = $this->form;
$formRutinas->prepare();
$hiddenInfoRegistro = '';
$action = $formRutinas->getAttribute('action');
if ($action == 'add') {
    $hiddenInfoRegistro = 'hidden';
}

echo $this->form()->openTag($formRutinas);
?>

<fieldset>
    <legend>Informacion del Rutinas</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="DESCRIP_RUTINA">Detalle Rutina</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($formRutinas->get('DESCRIP_RUTINA')); ?>
        </div>
    </div>   

</fieldset>
<fieldset <?php echo $hiddenInfoRegistro; ?>>
    <legend>Informacion de Registro</legend>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="pk_rutina_id">ID Rutina</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($formRutinas->get('pk_rutina_id')); ?>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fechaRutina">Fecha</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <?php echo $this->formRow($formRutinas->get('fechaRutina')); ?>
        </div>
    </div>
</fieldset>
<div class="ln_solid"></div>
<div class="ln_solid"></div>
<?php echo $this->form()->closeTag(); ?>
