
<h4>RUTINA DE: <u>{NOM_USU} {APELL_USU}</u></h4>
<h4>RUTINA N°: <u>{pk_rutina_id}</u></h4>
<h4>DESCRIPCION: <u>{DESCRIP_RUTINA}</u></h4>

<table style="font-size: 11px !important">
    <tr>
        <td colspan="2" class="tdTitulo">INFORMACION DEL USUARIO</td>
    </tr>
    <tr>
        <td class="tdCampo">APELLIDOS</td>
        <td>{APELL_USU}</td>
    </tr>
    <tr>
        <td class="tdCampo">NOMBRES</td>
        <td>{NOM_USU}</td>
    </tr>
    <tr>
        <td class="tdCampo">CEDULA</td>
        <td>{IDENTIFICACION}</td>
    </tr>
    <tr>
        <td class="tdCampo">DIRECCION</td>
        <td>{DIR_USU}</td>
    </tr>
    <tr>
        <td class="tdCampo">TELEFONO</td>
        <td>{TEL_USU}</td>
    </tr>
    <tr>
        <td class="tdCampo">E-MAIL</td>
        <td>{CORREO_USU}</td>
    </tr>
    <tr>
        <td class="tdCampo">TELEFONO</td>
        <td>{TEL_USU}</td>
    </tr>
    <tr>
        <td class="tdCampo">FECHA NACIMIENTO</td>
        <td>{FECHA_NAC_USU}</td>
    </tr>
    <tr>
        <td class="tdCampo">OCUPACION</td>
        <td>{ocupacion}</td>
    </tr>
    <tr>
        <td colspan="2" class="tdTitulo">INFORMACION DEL INSTRUCTOR</td>
    </tr>
    <tr>
        <td class="tdCampo">NOMBRE</td>
        <td>{NOM_INST} {APELL_INST}</td>
    </tr>
    <tr>
        <td class="tdCampo">TELEFONO</td>
        <td>{TEL_INST}</td>
    </tr>
    <tr>
        <td class="tdCampo">CEDULA</td>
        <td>{CORREO_INST}</td>
    </tr>
    <tr>
        <td class="tdCampo">CARGO</td>
        <td>Instructor GYM</td>
    </tr>
    <tr>
        <td colspan="2" class="tdTitulo">Ejercicios</td>
    </tr>
    <tr>
        <td colspan="4" class="tdTitulo">Rutina del Lunes</td>
    </tr>
    <tr>
        <td class="tdCampo">Ejercicio</td>
        <td class="tdCampo">Descripcion</td>
        <td class="tdCampo">Repeticiones</td>
        <td class="tdCampo">Imagen</td>

    </tr>
    <tr>
        <td>{NOM_EJER}</td>
        <td>{DESC_EJER}</td> 
        <td>4x10</td>
        <td> <img src="public/img/ejercicios/{RUTA_IMG_EJER}" width="50" height="50"> </td> 

    </tr>
    <tr>
        <td colspan="4" class="tdTitulo">Rutina del Martes</td>
    </tr>
    <tr>
        <td class="tdCampo">Ejercicio</td>
        <td class="tdCampo">Descripcion</td>
        <td class="tdCampo">Repeticiones</td>
        <td class="tdCampo">Imagen</td>

    </tr>
    <tr>
        <td colspan="4" class="tdTitulo">Rutina del Miercoles</td>
    </tr>
    <tr>
        <td class="tdCampo">Ejercicio</td>
        <td class="tdCampo">Descripcion</td>
        <td class="tdCampo">Repeticiones</td>
        <td class="tdCampo">Imagen</td>

    </tr>
    <tr>
        <td colspan="4" class="tdTitulo">Rutina del Jueves</td>
    </tr>
    <tr>
        <td class="tdCampo">Ejercicio</td>
        <td class="tdCampo">Descripcion</td>
        <td class="tdCampo">Repeticiones</td>
        <td class="tdCampo">Imagen</td>

    </tr>
    <tr>
        <td colspan="4" class="tdTitulo">Rutina del Viernes</td>
    </tr>
    <tr>
        <td class="tdCampo">Ejercicio</td>
        <td class="tdCampo">Descripcion</td>
        <td class="tdCampo">Repeticiones</td>
        <td class="tdCampo">Imagen</td>

    </tr>
    <tr>
        <td colspan="4" class="tdTitulo">Rutina del Sabado</td>
    </tr>
    <tr>
        <td class="tdCampo">Ejercicio</td>
        <td class="tdCampo">Descripcion</td>
        <td class="tdCampo">Repeticiones</td>
        <td class="tdCampo">Imagen</td>

    </tr>
    <tr>
        <td colspan="4" class="tdTitulo">Rutina del Domingo</td>
    </tr>
    <tr>
        <td class="tdCampo">Ejercicio</td>
        <td class="tdCampo">Descripcion</td>
        <td class="tdCampo">Repeticiones</td>
        <td class="tdCampo">Imagen</td>

    </tr>
</table>


<div style="page-break-after: always;"></div>

<div style="page-break-after: always;"></div>



