<p class="text-muted font-13 m-b-30">
    A continuacion se listan todas las rutinas registradas en el sistema.
</p><br>
<div style="overflow: scroll">
    <table id="tblRutinas" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>DESCRIPCION</th>
                <th>FECHA</th>               
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->rutinas as $rutina) {
                echo '<tr>';
                echo '<td>' . $rutina['rutinasOBJ']->getPk_rutina_id() . '</td>';
                echo '<td>' . $rutina['rutinasOBJ']->getDESCRIP_RUTINA() . '</td>';
                echo '<td>' . $rutina['rutinasOBJ']->getfechaRutina() . '</td>';
                echo '<td>';
                echo '<a href="" onclick="selectRutina(' . $rutina['rutinasOBJ']->getPk_rutina_id() . '); return false;" title="Seleccionar esta Rutina"><i class="fa fa-check"></i></a>';
                echo '</td>';
                echo '</tr>';
            }
            ?>
        </tbody>
    </table>
</div>